---
title: "A Quote Diary"
subtitle: "Zettel#94"
date: 2023-06-06
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
I used to archive numerous quotes in my very old notes. If I happen to rediscover them while rummaging through those archives, I will try to add some of them here. I will also try to add new ones.

___

> Comment prétendons-nous qu'un autre garde notre secret si nous ne pouvons le garder nous-mêmes ?
>
> La Rochefoucauld

___

> Excellence in any department can be attained only by the labor of a lifetime; it is not to be purchased at a lesser price.
>
> Samuel Johnson

___

> On n’est point un homme d’esprit pour avoir beaucoup d'idées, comme on n’est pas un bon général pour avoir beaucoup de soldats.
>
> Chamfort

___

> Ce qui fait le succès de quantité d’ouvrages est le rapport qui se trouve entre la médiocrité des idées de l’auteur et la médiocrité des idées du public.
>
> Chamfort

=> Il faut des auteurs médiocres pour les gens médiocres.
___

> On se fâche souvent contre les gens de lettres qui se retirent du monde. On veut qu’ils prennent intérêt à la société dont ils ne tirent presque point d’avantage ; on veut les forcer d’assister éternellement aux tirages d’une loterie où ils n’ont point de billet.
>
> Chamfort

___

> Il y a une mélancolie qui tient à la grandeur de l’esprit.
>
> Chamfort

___

> There is no such thing on earth as an uninteresting subject; the only thing that can exist is an uninterested person.
>
> Chesterton, in *Heretics*, chapter 3

___

> The reason angels can fly is because they take themselves lightly.
>
> Chesterton

___

> Lorsqu'une fois on a tâté des œuvres sérieuses, rarement continue-t-on à se plaire à la farce, surtout celle du genre ennuyeux.
>
> Schopenhauer

___

> Il n'y a pas meilleure investissement que de se faire voler son argent, car alors on s'est acheté de la prudence.
>
> Schopenhauer

___

I don't remember the original quote, but I always remembered my interpretation of it:

> Si la vie n'a aucun sens, alors cette phrase n'en a guère davantage.
>
> Alan Watts

___

> Coding is to programming what typing is to writing.
>
> Leslie Lamport
> [source](https://youtu.be/rkZzg7Vowao?si=OIocBMBivtIcgONe)

## Related Zettel

* [Zettel#9](/zettel/9)
* [Zettel#36](/zettel/36)
