---
title: "A Very Simple Windows Management Workflow for Windows"
subtitle: "Zettel#47"
id: "47"
date: 2023-03-14
date-modified: ""
date-format: iso
categories: [zettelkasten]
spotlight: "⭐"
---
Having efficient keybinds can be a significant factor in performing actions quickly. Compared to having to click on an icon, being able to display a specific application / window with a keybind makes for a smooth workflow. You don't have to search for the icon on your screen, move your mouse, and finally click on it. Here, you just press a keybind, and you're done.

Well you can have this in Windows without installing anything.

## Create keybinds for apps pinned in the taskbar

1. right-click on an app and pin it to the taskbar;
2. organize it so that, if it's in the first position, its assigned keybind will be 1;
3. call the app with `win + n` where `n` matches its position in your taskbar;
4. press `win + shift + n` to create a new instance of the app (viz. in a new window, if it's possible).

Don't put things that already have a keybind, like the **File Explorer** which you can access with `win + e`.

### Some of my own keybinds

* `win + 2` is assigned to my web browser dedicated to work;
* `win + 3` is assigned to Windows Terminal;
* `win + 4` is assigned to Discord;
* `win + 5` is assigned to the Calculator;
* `win + 9` is assigned to my other web browser;
* `win + 0` is assigned to Spotify.

### Web browsers: separating work and personal use

My web browser dedicated to work doesn't restore the previous session. Instead, it opens with two tabs: ChatGPT and Google. As someone who struggles to manage a healthy number of tabs (and even windows), having this setup alleviates my cognitive load. I close the browser almost after every search so that I can have a clean slate for the next one.

## Moving your windows

### Windows Snap

You can easily move your windows by pressing `win + arrow keys` and `win + alt + arrow keys` . All of this is native to Windows, and there are also preconfigured layouts you can toggle with `win + z`.

**More on this here:**
<https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241#WindowsVersion=Windows_11>

## Going further

You can have a lot more by installing PowerToys (developed by Microsoft). Some of my favorite features from PowerToys:

* Keyboard Manager, to remap keys and create new keybinds;
* Color Picker, `win + shift + c`;
* Quick Accent, so I don't have to use `alt + 128` to print a 'Ç', `alt + 144` for a 'É', and so on;
* Run, which is a fast app launcher you access with `alt + space`;
* Text Extractor, which is an Optical Character Recognition tool.

I personally don't use FancyZones much, but if a more advanced tiling window manager than FancyZones appeal to you, you might be interested by **komorebi**.

* PowerToys: <https://learn.microsoft.com/en-us/windows/powertoys/install>
* komorebi: <https://github.com/LGUG2Z/komorebi>

## Related Zettel

* [Zettel#87](/zettel/87)
* [Zettel#81](/zettel/81)
* [Zettel#78](/zettel/78)
* [Zettel#16](/zettel/16)
