---
title: "The rise of domain experts in deep learning"
subtitle: "[Zettel#8](/zettel/8)"
date: 2022-08-21
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
**Interview with Jeremy Howard, the founder of fast.ai.**

https://future.com/the-rise-of-domain-experts-in-deep-learning

Article qui présente une histoire accélérée des praticiens du deep learning : des chercheurs aux *prompt engineers*. C'est une expression qu'on voit souvent depuis les débats enflammés autour des IA de générations d'images qui voleraient les artistes – mon emploi du conditionnel dénote ma posture éthique, car je trouve que les discussions autour du scraping relèvent d'un problème accessoire de légaliste. C'est à une toute autre échelle, mais n'importe quel artiste apprend par le pastiche sans jamais qu'il ne soit question de droits d'auteurs. Le véritable enjeu se trouve dans l'accès aux données : les grosses entreprises ont les moyens de récolter des données colossales pour construire leurs modèles ; mais sans les mettre à la disposition de tout un chacun, elles créent un problème de démocratie majeur.

Certains détracteurs et "lanceurs d'alertes" utilisent parfois cette qualification de *prompt engineer* pour nommer avec sarcasme les personnes qui se servent de ces IA pour créer des images, et ainsi retirer toute la créativité de leur agentivité. Pour moi, il est plutôt clair que c'est la machine qui est le réel "artiste", tandis que les *prompt engineers* ont un rôle de directeur artistique – à la façon d'un réalisateur de cinéma. Ici, Jeremy Howard parle du *prompt engineering* comme d'un ensemble de compétences, sans aucun mépris, que tout le monde va devoir développer par la force des choses. C'est une question d'interactions homme-machine, dit-il, de la même manière que nous avons dû apprendre à nous servir des interfaces graphiques, de nos smartphones, etc.

#deep-learning #machine-learning #AI #prompt-engineer
