---
title: "Vim `:g` Command: A Practical Guide"
subtitle: "Zettel#128"
id: "128"
date: 2023-10-05
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
The `:g` command in Vim is a powerful tool for performing actions on lines that match a particular pattern. Below are some practical examples to demonstrate its utility.

## Inserting a New Line Below Markdown Headings

```vim
:g/^#/normal o
```

**Description**: Useful in Markdown files to insert a new line below each heading, ensuring that headings and paragraphs are separated.

## Deleting Empty Lines

```vim
:g/^\n\n/normal dd
```

**Description**: Deletes one of each set of consecutive empty lines, reducing them to single empty lines.

## Changing Bullet Point Style in Unordered Lists

```vim
g/^\s*-/s/-/*/
```

**Description**: Changes the bullet point style from `-` to `*` in unordered lists, which is particularly useful when you want to standardize the list format.

## Displaying Lines Containing a Specific Word

```vim
:g/word/#
```

**Description**: Displays line numbers and content for lines containing the word "word."

## Related Zettel

* [Zettel#30](/zettel/30)
* [Zettel#35](/zettel/35)
* [Zettel#40](/zettel/40)
* [Zettel#42](/zettel/42)
* [Zettel#44](/zettel/44)
* [Zettel#45](/zettel/45)
* [Zettel#51](/zettel/51)
* [Zettel#60](/zettel/60)
* [Zettel#79](/zettel/79)
* [Zettel#122](/zettel/122)
