---
title: "Jedi-Vim Plugin Cheat Sheet"
subtitle: "Note#102"
id: "102"
date: 2023-06-23
date-modified: ""
date-format: iso
categories: [notes]
---
## Keybindings

1. **`<leader>d`**: Use this to navigate to the definition of a function or method under the cursor. It goes as far as possible to the original definition—it therefore might open a new buffer with another file.
1. **`<leader>g`**: This is a typical "goto" function. It looks for the definition in the same file.
1. **`<leader>r`**: Deletes the word under the cursor and awaits new variable name in Vim's insert mode. Once provided, it replaces all occurrences project-wide.
1. **`<leader>R`**: Keeps the word under the cursor, moves to its end, and awaits new variable name in Vim's insert mode. Once provided, it replaces all occurrences project-wide.
1. **`<leader>n`**: List all usages of the name under the cursor in a file.
1. **`K`**: This keybinding is used to display the documentation for the function or method under the cursor.
1. **`<ctrl-space>`**: Triggers Jedi-vim autocompletion, aiding in the quick completion of Python code variables, functions, and more.
1. **`:Pyimport os`**: This command is used to import and open the `os` module. It allows for the direct interaction and experimentation with Python modules within Vim.

## Additional Information

To access the built-in documentation of Jedi-Vim in Vim, use the following command:

```vim
:help jedi
```

## Related Notes

* [Note#62](/notes/62)
* [Note#69](/notes/69)

## References

* <https://github.com/davidhalter/jedi-vim>
