---
title: "Automating a Reading Note Template Generation Using Zotero Metadata"
subtitle: "Note#146"
id: "146"
date: 2024-03-27
date-modified: ""
date-format: iso
categories: [notes]
---
I wanted to easily write some notes for any article when I feel like it, in the same way I already do with anything else. However, I wanted to have a template with some metadata about the article. This metadata would contain elements like the title, the publication date, keywords, URL, and abstract.

## Requirements

* Zotero
* BetterBibTex
* A script to parse the BetterBibTex export and generate the notes

## Workflow

I use Zotero and the "Save to Zotero" web browser extension to archive articles I might be interested in reading.

This workflow also needs the BetterBibTex plugin for Zotero, which allows me to export the metadata of the articles in a format that I can easily parse. BetterBibTex automatically updates the export file when I add an article in Zotero.

Now, when I want to write some notes on an article, here is what I do:

* Open the BetterBibTex export file.
* Search for the article I want to write about.
* Select the metadata.
* Run a script that generates a note template with the selected metadata.
