---
title: "Learn Git and GitHub"
subtitle: "Zettel#91"
date: 2023-05-27
date-modified: ""
date-format: iso
categories: [zettelkasten]
"&nbsp;": "⭐"
---
## Git Documentation and Learning Resources

### Free Resources

* [Version Control – Missing Semester (MIT)](https://missing.csail.mit.edu/2020/version-control/): An in-depth tutorial from MIT's Missing Semester series, focusing on the concept of version control with Git. It provides a comprehensive overview and practical guidance on handling projects with Git.
* [Git Basics | The Odin Project](https://www.theodinproject.com/lessons/foundations-git-basics): As part of The Odin Project's Foundations course, this tutorial offers hands-on exercises to cement the understanding of Git basics. This resource is a great learning tool for those wanting to practice and reinforce Git commands and workflows.
* [Lecture on Git, as part of CS50W](https://cs50.harvard.edu/web/2020/notes/1/): It's the second week of the course CS50W, teaching about Git and GitHub.
* [Pro Git (Chacon & Straub)](https://git-scm.com/book/en/v2): The book covers all aspects of Git, from basic commands and workflows to advanced features like rebasing, submodules, and server administration. It's highly recommended for both beginners looking for a comprehensive introduction and experienced users wanting a handy reference.
* `man gittutorial`: As a hands-on introduction to Git, it introduces fundamental concepts and basic usage scenarios. It is an ideal step-by-step guide for Git beginners.
* `man giteveryday`: A useful guide that offers a set of commands for typical Git usage scenarios. It's a handy manual for everyday Git tasks.
* `man gitworkflows`: This manual unravels different workflows in Git, aiding in understanding how Git can be efficiently deployed in a team environment.
* `man git`
* 3 short lessons on Git from MIT 6.102:
  * [Git 1: Version Control](https://web.mit.edu/6.102/www/sp23/tools/git-1-version-control/)
  * [Git 2: Disaster Recovery](https://web.mit.edu/6.102/www/sp23/tools/git-2-disaster-recovery/)
  * [Git 3: Team Version Control](https://web.mit.edu/6.102/www/sp23/tools/git-3-team-version-control/)

### Not Free Resources

* [Boost your Git DX, by Adam Johnson](https://adamchainz.gumroad.com/l/bygdx): This book is definitely worth reading if you're seeking to learn about Git from a workflow-oriented perspective.
* [How Git Works, by Julia Evans](https://wizardzines.com/zines/git/): A short and easy read about the fundamentals of Git.
* [Everything You'll Need to Know About Git](https://frontendmasters.com/courses/everything-git/): ThePrimeagen teaching Git on Frontend Masters.
* [Learn Git](https://www.boot.dev/learn/learn-git): Again, ThePrimeagen teaching Git but on <boot.dev>.

## GitHub

### GitHub Skills

> Learn how to use GitHub with interactive courses designed for beginners and experts.
>
> [GitHub Skills](https://skills.github.com/) 

These courses are a great way to familiarize yourself with the GitHub environment.

### GitHub CLI: `gh` 

Almost everything you can do on the GitHub website, you can do it in a CLI with `gh`. 

> GitHub CLI is a command-line tool that brings pull requests, issues, GitHub Actions, and other GitHub features to your terminal, so you can do all your work in one place.
>
> <https://docs.github.com/en/github-cli/github-cli/about-github-cli>

* `man gh`
* [GitHub CLI manual](https://cli.github.com/manual/): This is the official online manual for GitHub CLI, a comprehensive guide that covers installation, usage, and command examples.

### GitHub Docs

> Help for wherever you are on your GitHub journey
>
> [GitHub Docs](https://docs.github.com/en)

## Related Zettel

* [Zettel#72](/zettel/72)
* [Zettel#125](/zettel/125)
