---
title: "Remapping the `²` Key on an AZERTY Keyboard with AutoHotkey (Windows)"
subtitle: "Zettel#87"
id: "87"
date: 2023-05-19
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
This guide explains how to create and automatically run an AutoHotkey script to map the `²` key on an AZERTY keyboard to insert a backtick `` ` ``.

Why not using the Windows PowerToys Keyboard Manager? Because it cannot create this kind of combination.

## Installing AutoHotkey

<https://www.autohotkey.com/>

## Creating the script

Open a new text file and insert the following code snippet:

```ahk
; Pressing the ² key sends the backtick (`) character.
; This is useful for AZERTY keyboards, for the ² key is useless.
²::
Send, `{ASC 96}
return
```

Save this script with a `.ahk` extension.

## Running the script

Run the saved script with AutoHotkey. It will stay active as long as the script is running.

## Automatically starting the script when Windows starts

1. Press `Win + R` to open the Run dialog box.
2. In the Run dialog, type `shell:startup` and hit Enter. This will open the Startup folder.
3. Paste the script file in the Startup folder.

This will create a shortcut to your script in the Startup folder and run your script automatically every time Windows starts.

## Related Zettel

* [Zettel#3](/zettel/3)
* [Zettel#47](/zettel/47)
* [Zettel#81](/zettel/81)
* [Zettel#78](/zettel/78)
* [Zettel#16](/zettel/16)
