---
title: "`w3m` Cheatsheet"
subtitle: "[Zettel#108](/zettel/108)"
date: 2023-07-28
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
## Navigation

* `j` - Cursor down
* `k` - Cursor up
* `h` - Cursor left
* `l` - Cursor right
* `K` - Scroll the screen down one line
* `J` - Scroll the screen up one line
* `g` - Go to the first line
* `G` - Go to the last line
* `[` - Move to the first hyperlink
* `]` - Move to the last hyperlink
* `TAB` - Move to the next hyperlink

## Hyperlink Operations

* `Enter` - Follow current hyperlink in a new buffer
* `c` - Show current address
* `u` - Show target address
* `i` - Show image address
* `=` - Display information about the current document

## File/Stream Operations

* `U` - Open specified document in a new buffer
* `V` - Open local file in a new buffer
* `|` - Pipe current buffer through a shell command and display output

## Buffer Operations

* `B` - Close current buffer and return to the one below in stack
* `s` - Pop up buffer-stack menu
* `v` - Toggle between HTML shown or processed
* `S` - Save rendered document
* `E` - Edit local source
* `R` - Load current document anew

## Tab Operations

* `T` - Open a new tab (with current document)
* `C-t` - Open the link in a new tab
* `}` - Switch to the next tab
* `{` - Switch to the previous tab
* `Esc-t` - Pop up tab selection menu

## Bookmark Management

* `ESC-b` - View bookmarks
* `ESC-a` - Add current page to bookmarks
* To delete or rename a bookmark, view bookmarks, navigate to the bookmark you want to modify, press `E` and perform your desired action.

## Searches

* `/` - Search forward
* `?` - Search backward
* `n` - Continue search forward
* `N` - Continue search backward

## Miscellaneous

* `M` - Open the current page in the external (GUI) web browser
* `H` - Show help panel
* `o` - Display options setting panel
* `r` - Display the version of w3m
* `q` - Quit with confirmation request
* `Q` - Quit without confirmation
* `C-k` - View cookie list
* `C-h` - Show browsing history

## References

* <https://w3m.sourceforge.net/MANUAL#Key:orig>
