---
title: "Basic Time Frames of Emotion"
subtitle: "[Zettel#137](/zettel/137)"
date: 2023-10-20
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
I found a very old note from my early years when I was studying psychology. I'm not sure whether I wrote this note myself or quoted it from an article or book. Regardless, I believe it's worth archiving here.

## Emotional State

Typically lasting only a few seconds, it tends to be triggered by an experience; it can also arise from purely mental activity, such as daydreaming, or introspection, or anticipating the future.

But whether they are triggered by real-world experiences or mental ones, emotional states tend to dissipate, each giving way to the next.

## Mood

A feeling that does persist, and that remains consistent over minutes or hours or even days, is a mood, of the "he's in a bad mood" variety.

## Emotional Trait

And a feeling that characterizes you not for days but for years is an emotional trait => increases the likelihood that you will experience a particular emotional state (e.g. Fury) because it lowers the threshold needed to feel such an emotional state.

## Emotional Style

It is a consistent way of responding to the experiences of our lives. It is governed by specific, identifiable brain circuits and can be measured using objective laboratory methods. An emotional style influences the likelihood of feeling particular emotional states, traits and moods. Because emotional styles are much closer to underlying brain systems than emotional states or traits, they can be considered the atoms of our emotional lives—fundamentals building blocks.
