---
title: "How to use macros in Vim"
subtitle: "Note#60"
id: "60"
date: 2023-04-07
date-modified: ""
date-format: iso
categories: [notes]
---
## Record a macro

1. Press `q` followed by a letter to start recording.
2. Perform the desired operations.
3. Press `q` again to stop recording.

## Running a macro

1. Press `@` followed by the letter of the macro.
2. Press `@@` to run the last executed macro again.

## Apply a macro to a set of lines

1. In visual mode, select the lines.
2. Press `:` followed by `normal @` and the letter of the macro.

## Viewing a macro

1. Type `:registers` or `:reg` to see the contents of all registers.
2. Type `:reg <letter>` to see the contents of a specific register.

## Saving a macro

1. Type `:let @<letter>='macro_contents'`, replacing `<letter>` with the register and `macro_contents` with the actual content of the macro.
2. To insert the contents of an existing macro, type `:let @<letter>='` and then press `Ctrl-R Ctrl-R <letter>` to insert the contents literally.
3. Add the above line to your `.vimrc` file to load the macro automatically when Vim starts.

## Appending to a macro

1. Press `q` followed by the capital letter of the macro to start appending.
2. Perform the additional operations.
3. Press `q` again to stop appending.

## Editing a macro

1. Paste the macro contents into a new buffer or just a blank line using `"ap` (replace 'a' with the appropriate letter).
2. Edit the macro as needed.
3. Yank the modified macro back into the register using `"ay$` (replace 'a' with the appropriate letter). Compared to `"ayy`, this will avoid yanking a trailing newline character.
