---
title: "Moby Dick, extrait de la première page"
subtitle: "[Zettel#9](/zettel/9)"
date: 2022-08-23
date-modified: ""
date-format: iso
categories: [zettelkasten]
---
*Dans la traduction d'Armel Guerne.*

> C'est un remède à moi ; c'est une manière que j'ai de me sortir du noir et de redonner du tonus à la circulation de mon sang. Oui, chaque fois que je me sens la lèvre amère et dure  ; chaque fois qu'il bruine et vente dans mon âme et qu'il y fait un novembre glacial ; chaque fois que, sans préméditation aucune, je me trouve planté devant la vitrine des marchands de cercueils ou emboîtant le pas aux funèbres convois que je rencontre ; et surtout, oui, surtout, chaque fois que je sens en moi les mauvaises humeurs l'emporter à ce point qu'il me faille le puissant secours des principes moraux pour me retenir d'aller courir les rues à seule fin de jeter bas, fort méthodiquement, le chapeau des gens -, alors, oui, je considère qu'il est grand temps pour moi de filer en mer au plus vite. C'est ce qui me tient lieu de pistolet et de plomb.

## Related Zettel

* [Zettel#36](/zettel/36)
* [Zettel#94](/zettel/94)
