project:
  type: website

website:
  title: "Sébastien De Revière"
  site-url: https://sderev.com
  description: "Personal website of Sébastien De Revière"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/sderev
      - icon: twitter
        href: https://twitter.com/sdereviere
  twitter-card:
    creator: "@sdereviere"
  reader-mode: false

  page-footer: 
    border: true
    center:
      - icon: github
        href: https://github.com/sderev
      - icon: twitter
        href: https://twitter.com/sdereviere

format:
  html:
    theme: [cosmo, styles.css]
    css: styles.css

    html-math-method: katex

    email-obfuscation: javascript

    mainfont: Crimson Pro
    fontcolor: "#222"
    fontsize: 1.6rem
    linestretch: 1.6

    anchor-sections: true
    smooth-scroll: true
    page-layout: full

    toc: true
    toc-location: right
    toc-expand: true
    toc-title: Contents

    code-block-background: true
    code-block-bg: GhostWhite
    code-copy: true
    code-line-numbers: true
    highlight-style: arrow
    monobackgroundcolor: GhostWhite
    monofont: Fira Code

    link-external-icon: true
